(()=>{const C=StudyNookConfig;let config={...C.defaultAvatar,...(AvatarStorage.load()||{})},category="hair",xp=null;const $=s=>document.querySelector(s);function unlocked(i){return xp!==null&&xp>=i.xpRequired}function equipped(i){return i.multi?(config.accessories||[]).includes(i.id):config[i.category]===i.id}
function renderTabs(){ $("#tabs").innerHTML=C.categories.map(c=>`<button class="tab ${c===category?'active':''}" data-cat="${c}">${c==='hijab'?'Hijab / Headwear':c[0].toUpperCase()+c.slice(1)}</button>`).join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderTabs();renderItems()})}
function renderItems(){const list=C.items.filter(i=>i.category===category);$("#items").innerHTML=list.map(i=>{const ok=unlocked(i),eq=equipped(i);return `<button class="item ${ok?'':'locked'} ${eq?'equipped':''}" data-id="${i.id}" ${ok?'':'aria-disabled="true"'}><span class="thumb"><img src="${i.asset}" alt="${i.name}">${ok?'':`<b class="lock">🔒</b>`}</span><strong>${i.name}</strong><small>${eq?'✓ Equipped':ok?'✓ Unlocked':`${i.xpRequired} XP required`}</small>${!ok&&xp!==null?`<em>${Math.max(0,i.xpRequired-xp)} XP to go</em>`:''}</button>`}).join("");document.querySelectorAll(".item").forEach(b=>b.onclick=()=>equip(b.dataset.id))}
function equip(id){const i=C.items.find(x=>x.id===id);if(!i||!unlocked(i))return;if(i.multi){const a=new Set(config.accessories||[]);a.has(id)?a.delete(id):a.add(id);config.accessories=[...a]}else{config[i.category]=config[i.category]===id&&["bags","glasses","hijab"].includes(i.category)?null:id;if(i.category==="hijab"&&config.hijab){} }AvatarRenderer.renderAvatar(config);renderItems()}
function renderXP(){const status=$("#status"),label=$("#xpLabel"),next=$("#nextUnlock"),bar=$("#xpBar");if(xp===null){label.textContent="Waiting for XP…";status.textContent="🟡 Waiting for Study Nook XP connection";bar.style.width="0%";return}label.textContent=`⭐ ${xp.toLocaleString()} XP`;status.textContent=XPIntegration.isConnected()?"🟢 Connected to Study Nook":"🔵 Development Mode — Test XP";const future=C.items.filter(i=>i.xpRequired>xp).sort((a,b)=>a.xpRequired-b.xpRequired);if(future[0]){const n=future[0];const prev=Math.max(0,...C.items.filter(i=>i.xpRequired<=xp).map(i=>i.xpRequired));const pct=Math.min(100,Math.max(0,(xp-prev)/(n.xpRequired-prev)*100));bar.style.width=pct+"%";next.textContent=`Next unlock: ${n.name} at ${n.xpRequired.toLocaleString()} XP`}else{bar.style.width="100%";next.textContent="All current rewards unlocked ✨"}$("#rewards").innerHTML=future.slice(0,3).map(i=>`<div><span>🔒 ${i.xpRequired.toLocaleString()} XP</span><b>${i.name}</b></div>`).join("")||"<p>Everything is unlocked! ♡</p>";renderItems()}
function save(){AvatarStorage.save(config);XPIntegration.send("AVATAR_UPDATED",{avatar:config});$("#saveNote").textContent="Saved! Your avatar configuration is ready for Study Nook ♡";setTimeout(()=>$("#saveNote").textContent="",3000)}
function reset(){if(!confirm("Reset your avatar to the default look?"))return;config=structuredClone(C.defaultAvatar);AvatarRenderer.renderAvatar(config);renderItems();save()}
$("#saveBtn").onclick=save;$("#resetBtn").onclick=reset;window.addEventListener("studynook:set-avatar",e=>{config={...C.defaultAvatar,...e.detail};AvatarRenderer.renderAvatar(config);renderItems()});window.addEventListener("studynook:request-avatar",()=>XPIntegration.send("AVATAR_UPDATED",{avatar:config}));
window.StudyNookAvatar={getAvatarConfig:()=>structuredClone(config),setAvatarConfig(c){config={...C.defaultAvatar,...c};AvatarRenderer.renderAvatar(config);renderItems()},getUnlockedItems:()=>C.items.filter(unlocked).map(i=>i.id),getCurrentXP:()=>xp};
renderTabs();AvatarRenderer.renderAvatar(config);XPIntegration.onChange((v)=>{xp=v;renderXP()});renderXP();XPIntegration.start();})();
